# Generated by Django 2.1 on 2020-11-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
